sonar.projectKey=shell-angular21
sonar.projectName=shell-angular21
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.app.json

sonar.exclusions=dist/**,node_modules/**,trivy/**
